name: GameUpdater
on:
  workflow_dispatch:

jobs:
  # checkout:
  #   name: build files.xml for updater
  #   runs-on: tony-vm
  #   steps:
  #     - uses: actions/checkout@v3
  #       name: checkout
  #       with:
  #         fetch-depth: 0
  getchanges:
    name: get all changed file from Updater
    runs-on: tonyuvm
    steps:
      - name: get changes
#        working-directory: ..
        run: echo ${{ github.ref }}
        # run: |
        #   Get-Location
        #   $FileExist = Test-Path latest_sha.txt
        #   echo "FileExist la $FileExist"
          
        #   if ($FileExist) { 
        #     $sha = Get-Content latest_sha.txt
        #     echo "noi dung file la $sha"
        #     Add-Content -Path $env:GITHUB_ENV -Value "curr_sha=$sha" 
        #   } 
        #   echo "curr_sha la ${{ env.curr_sha }}"
        #   $latestSHA = git rev-parse --short HEAD
        #   echo "latestSHA la $latestSHA"
        #   $FilesChanged = git diff --name-only $latestSHA
        #   echo "FilesChanged la $FilesChanged"

# for debug
# $fileExist = Test-Path latest_sha.txt
# echo "fileExist la $fileExist"

#else { echo "$(git rev-list --max-parents=0 HEAD) = " ${{ env.curr_sha }} }
# echo  "the var was detected to be test = " ${{env.MYVAR}}
#        ${{ env.minRamGS }}

  # final:
  #   name: update SHA for latest commit for next run
  #   runs-on: tony-vm
  #   needs: [getchanges]
  #   steps:
  #     - name: update SHA
  #       working-directory: ..
  #       run: ${{ env.TestUpdater.steps.latestSHA }} > latest_sha.txt
    
