name: GameUpdater
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  TestUpdater:
    # The type of runner that the job will run on
    runs-on: tony-vm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Module
        run: |
          Get-Location
          $FilesChanged = git diff --name-only 59668e6
          $FilesChanged


